apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-helloworld
  labels:
    app: maven
spec:
  selector:
    matchLabels:
      app: maven
  replicas: 2
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven
        image: escs34/hello_maven:v0.1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        #만약 private repo면 여기에 secret추가하면 된다.
