apiVersion: v1
kind: Service
metadata:
  name: argo-external
  #ingress가 있는 네임스페이스
  namespace: jenkins
spec:
  type: ExternalName
  #servicename.namespace.svc,cluster.local
  externalName: argocd-server.argocd.svc.cluster.local