apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: local-sc
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/volumes/pv1
