apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-storageclass-dynamic